### ISSUE TITLE
Passing an empty list as parmeter

### ISSUE THREAD

**Issue by woutermont** [LinkedSoftwareDependencies/Components.js#47]
#### Issue type:

- :heavy_plus_sign: Feature request 

____
#### Description:

When a constructor requires a (mandatory) list as argument, currently the instantiattion fails if the list passed in the configuration is empty (`"ClassName:_listParam": []`). Is there a workaround for this behavior?

**Comment by rubensworks** [comment]
Marking a parameter as required actually means that there should be _at least one_ value.

Due to the semantics of JSON-LD and RDF, `"ClassName:_listParam": []` will produce no triples, which makes validation of the parameter requirement fail.

I presume that in this case, you probably want to make the parameter optional.

**Comment by woutermont** [comment]
That would mean there is no semantic difference between an empty list and no list at all ...

**Comment by joachimvh** [comment]
The thing you see in the Components.js config is actually not a list semantically speaking. In JSON-LD the brackets are used to create multiple triples with the same predicate. To have a list you need the [@list](https://www.w3.org/TR/json-ld/#lists) keyword. Components.js is just nice enough to interpret all those triples as a list of values instead of separate values (I'm guessing because the @list syntax would make it a lot uglier), even though semantically that's not really a list. The disadvantage of that technique though is indeed that if there are no values (which is identical to writing `[]` in JSON-LD), it has no idea if this is an empty list or a value that is missing.

**Comment by rubensworks** [comment]
One solution would be to introduce the following behaviour:
If Components.js sees a field that is non-unique+required (what the generator outputs for array params), and has no passed values, it will consider it an empty array.

Concretely, this would mean that passing `"ClassName:_listParam": []` is equivalent to not defining a value for that field at all. In both cases, Components.js would pass an empty array to the constructor.

This is a minor change in semantics for Components.js (that would call for a major update), as non-unique+required fields would require _at least one value_ before. Since this check could be considered a bit arbitrary for arrays, it makes sense to apply this change in semantics.

If the "if the array contains at least one value" check would be necessary, then we could add this via a new `minimumElements` property or something like that. But AFAIK, no one really makes use of this functionality, so it probably doesn't hurt if it is removed/modified.

@woutermont @joachimvh Would such a change make sense to you?

**Comment by joachimvh** [comment]
The only time unique is false is when the input parameter is an array right? In that case this sounds like a reasonable solution. Only disadvantage is that you lose the error message in case you forget to define the parameter. 

I've never had a need yet for empty arrays but since it's currently impossible to define them I think this solution is better than the current situation.

**Comment by woutermont** [comment]
While I think it's semantically a bit strange, it would definitely be more workable than the current situation.

**Comment by rubensworks** [comment]
Actually, after thinking about it a bit more, I think the following solution might be cleaner:

For a given config:
```json
{
  "@type": "MyClass",
  "param1": []
}
```

The generator would set the JSON-LD container type to `@list` inside the type-scoped context entry of `param1`.
This would make the values a proper RDF list, which allows us to keep the "empty list" semantics.
(This generator change should be quite trivial)

Next, Components.js would require a small change, as it would now also need to support such RDF lists as input to parameters. I don't foresee major difficulties for this.

The advantage of this approach would be that Components.js will still throw an error if you don't define `param1` in your config if it's required. This is because this approach doesn't consider a missing `param1` and `"param1": []` as the same thing.

@joachimvh @woutermont Any thoughts?

**Comment by joachimvh** [comment]
Ah yea, that's definitely better. I just assumed that one wasn't an option :D
