### ISSUE TITLE
Error on circular dependency

### ISSUE THREAD

**Issue by joachimvh** [LinkedSoftwareDependencies/Components.js#53]
#### Issue type:

- :heavy_plus_sign: Feature request 

____
#### Description:

If there is a circular dependency in the Components.js config, e.g. A takes B as input and B takes A as input, the result would be that one of the two gets `undefined` as input value instead of the expected instance. It makes sense that they can't reference each other since one of them has to be instantiated first, but it would be nice if Components.js threw an error in such a case instead of using `undefined`.

The example above is quite simplistic of course, in practice this might occur in much larger chains.

**Comment by rubensworks** [comment]
This was intentional (see [here](https://github.com/LinkedSoftwareDependencies/Components.js/blob/0d196bfd41d0fc52f005e3e37f6081922e87d608/lib/construction/ConfigConstructorPool.ts#L40-L45)).
This behaviour was chosen to be compatible with Node's `require` behaviour for circular dependencies.

But I agree that it makes sense to throw an error instead. This would be a breaking change though.

**Comment by rubensworks** [comment]
Will be part of release 5.x.
